disable a compiler warning for libbpf
Avoids this build error on rawhide since a recent glibc update:

"""
 libbpf.c: In function ‘kallsyms_cb’:
 libbpf.c:8250:13: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  8250 |         res = strstr(sym_name, ".llvm.");
       |             ^
 libbpf.c: In function ‘avail_kallsyms_cb’:
 libbpf.c:11579:31: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
 11579 |                 if (!(sym_sfx = strstr(sym_name, ".llvm.")))
       |                               ^
 libbpf.c: In function ‘resolve_full_path’:
 libbpf.c:12167:35: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
 12167 |                         next_path = strchr(s, ':');
       |                                   ^
 cc1: all warnings being treated as errors
"""

Signed-off-by: Thorsten Leemhuis <fedora@leemhuis.info>