package YNL test framework files
Package the files that 308b7dee3e5c76 ("tools: ynl: add YNL test
framework") added to avoid this build error:

"""
error: Installed (but unpackaged) file(s) found:
   /usr/bin/test_ynl_cli
   /usr/bin/test_ynl_ethtool
   /usr/share/kselftest/ktap_helpers.sh
"""

Signed-off-by: Thorsten Leemhuis <fedora@leemhuis.info>